In [5]:
?rand()


```
rand([rng=GLOBAL_RNG], [S], [dims...])
```

Pick a random element or array of random elements from the set of values specified by `S`; `S` can be

  * an indexable collection (for example `1:n` or `['x','y','z']`), or
  * a type: the set of values to pick from is then equivalent to `typemin(S):typemax(S)` for integers (this is not applicable to [`BigInt`](@ref)), and to $[0, 1)$ for floating point numbers;

`S` defaults to [`Float64`](@ref).


In [6]:
?randn()

```
randn([rng=GLOBAL_RNG], [T=Float64], [dims...])
```

Generate a normally-distributed random number of type `T` with mean 0 and standard deviation 1. Optionally generate an array of normally-distributed random numbers. The `Base` module currently provides an implementation for the types [`Float16`](@ref), [`Float32`](@ref), and [`Float64`](@ref) (the default).


In [10]:
rand(15,2)

15×2 Array{Float64,2}:
 0.776667   0.174346  
 0.0151903  0.588688  
 0.153324   0.00706754
 0.708307   0.800129  
 0.0855697  0.943577  
 0.0440153  0.325243  
 0.843213   0.71478   
 0.48519    0.0235308 
 0.356743   0.429453  
 0.319877   0.670902  
 0.91307    0.612375  
 0.733986   0.805317  
 0.248181   0.227609  
 0.844932   0.742216  
 0.614687   0.888911  

In [11]:
randn(10,2)

10×2 Array{Float64,2}:
 -1.2381    -0.971871 
 -0.469659  -0.660431 
  1.23256    0.973738 
 -2.24864   -0.647919 
 -0.264641  -1.88565  
  0.369348  -0.800236 
  0.583404  -0.264977 
  0.556064  -0.0711095
 -0.846128  -1.09985  
  0.416121   0.945975 

In [12]:
a = rand(4,4)


4×4 Array{Float64,2}:
 0.35379   0.728584   0.359572  0.854098
 0.734155  0.590326   0.934152  0.290868
 0.789124  0.0812576  0.951962  0.148326
 0.73811   0.0613295  0.643565  0.163766

In [15]:
reshape(a,16,1)

16×1 Array{Float64,2}:
 0.35379  
 0.734155 
 0.789124 
 0.73811  
 0.728584 
 0.590326 
 0.0812576
 0.0613295
 0.359572 
 0.934152 
 0.951962 
 0.643565 
 0.854098 
 0.290868 
 0.148326 
 0.163766 

In [17]:
reshape(a,8,2)

8×2 Array{Float64,2}:
 0.35379    0.359572
 0.734155   0.934152
 0.789124   0.951962
 0.73811    0.643565
 0.728584   0.854098
 0.590326   0.290868
 0.0812576  0.148326
 0.0613295  0.163766

In [18]:
a

4×4 Array{Float64,2}:
 0.35379   0.728584   0.359572  0.854098
 0.734155  0.590326   0.934152  0.290868
 0.789124  0.0812576  0.951962  0.148326
 0.73811   0.0613295  0.643565  0.163766

In [19]:
b = [true false false false;false true false false;false false true false;false false false true]


4×4 Array{Bool,2}:
  true  false  false  false
 false   true  false  false
 false  false   true  false
 false  false  false   true

In [20]:
a*b

4×4 Array{Float64,2}:
 0.35379   0.728584   0.359572  0.854098
 0.734155  0.590326   0.934152  0.290868
 0.789124  0.0812576  0.951962  0.148326
 0.73811   0.0613295  0.643565  0.163766

In [21]:
a[b]

4-element Array{Float64,1}:
 0.35379 
 0.590326
 0.951962
 0.163766

In [22]:
a*b

4×4 Array{Float64,2}:
 0.35379   0.728584   0.359572  0.854098
 0.734155  0.590326   0.934152  0.290868
 0.789124  0.0812576  0.951962  0.148326
 0.73811   0.0613295  0.643565  0.163766

In [23]:
a.*b

4×4 Array{Float64,2}:
 0.35379  0.0       0.0       0.0     
 0.0      0.590326  0.0       0.0     
 0.0      0.0       0.951962  0.0     
 0.0      0.0       0.0       0.163766

In [24]:
eye(4)

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [25]:
a*eye(4)

4×4 Array{Float64,2}:
 0.35379   0.728584   0.359572  0.854098
 0.734155  0.590326   0.934152  0.290868
 0.789124  0.0812576  0.951962  0.148326
 0.73811   0.0613295  0.643565  0.163766

In [26]:
a.*eye(4)

4×4 Array{Float64,2}:
 0.35379  0.0       0.0       0.0     
 0.0      0.590326  0.0       0.0     
 0.0      0.0       0.951962  0.0     
 0.0      0.0       0.0       0.163766

In [27]:
eye(4)

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [28]:
a*inv(a)

4×4 Array{Float64,2}:
  1.0           0.0          -4.44089e-16   2.22045e-16
 -2.22045e-16   1.0          -5.55112e-16   1.66533e-16
  0.0          -1.11022e-16   1.0          -2.498e-16  
  0.0          -5.55112e-17   1.66533e-16   1.0        

In [29]:
c=rand(8)



8-element Array{Float64,1}:
 0.877963 
 0.875419 
 0.756878 
 0.0419372
 0.258979 
 0.8245   
 0.823317 
 0.543383 

In [30]:
length(c)

8

In [31]:
size(c)

(8,)

In [32]:
a

4×4 Array{Float64,2}:
 0.35379   0.728584   0.359572  0.854098
 0.734155  0.590326   0.934152  0.290868
 0.789124  0.0812576  0.951962  0.148326
 0.73811   0.0613295  0.643565  0.163766

In [33]:
size(a)

(4, 4)

In [34]:
length(a)

16

In [1]:
c= rand(8)

8-element Array{Float64,1}:
 0.593938
 0.448054
 0.843517
 0.320087
 0.151621
 0.115336
 0.876239
 0.151522

In [ ]:
i = 1;
while i <= length(c)
    #println(c[i])
    if c[i] > 0.5
        continue
    end
    println(c[i])
    i=i+1
end

In [ ]:
rand()